
CREATE TABLE proyects (
idProyect INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
slogan VARCHAR(50) NOT NULL,
repo TEXT NOT NULL,
demo TEXT NOT NULL,
tech VARCHAR(50) NOT NULL,
description VARCHAR(500) NOT NULL,
photo TEXT NOT NULL,
url TEXT NOT NULL
);

CREATE TABLE author (
idAuthor INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
job VARCHAR(45) NOT NULL,
image TEXT NOT NULL
);
